.PHONY:	clean

clean:
	rm -rf ROOT/*
	rm -rf histograms/*
	rm -rf SNOwGLoBES/*
	mkdir -p ROOT
	mkdir -p histograms/all_channels
	mkdir -p histograms/background/distances
	mkdir -p SNOwGLoBES/DUNE
	mkdir -p SNOwGLoBES/JUNO
	mkdir -p SNOwGLoBES/HyperK
